### PR TITLE
Added Filtering for Removed Articles From  API Call

### PR DESCRIPTION
**Pull request by mkaomwakuni**
Description

This pull request adds filtering for removed articles in the getTopHeadlines API call. The getTopHeadlines method now fetches the top headlines for a specific category and filters out articles that have been marked as removed. This ensures that only valid articles are returned to the app for display.

Changes Made

Updated the Headlines method in the RepositoryImpl class to filter out removed articles.

Added logic to check if the article's title or content contains the keyword "removed" to determine if it should be filtered out.

Testing
Tested the updated method with various scenarios, including articles with and without the "removed" keyword.
Ensured that valid articles are returned correctly while removed articles are filtered out as expected.

### CODE REVIEW

**Comment by Yesim02** [comment]
Overall, the implementation looks good for filtering out removed articles from the fetched data before displaying them. However, having implemented  that the search will appear with that since not yet implemented

**Review by Yesim02 — CHANGES_REQUESTED** [review]
Check for the search method, articles will still appear with removed articles

**Comment by mkaomwakuni** [comment]
Suggested Changes Updated

**Review by Yesim02 — APPROVED** [review]
Yeah that way. All Good

**Pull request merged**
